### ISSUE TITLE
Basic example sandbox missing required hooks

### ISSUE THREAD

**Issue by tilanka** [tannerlinsley/react-table#1404]
**Describe the bug**
The basic example sandbox is not using the required  `useColumns`  and  `useRows` hooks  which  is causing a fatal error

**To Reproduce**
1. Go to the basic example sandbox https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/basic
2. You can see the error straightaway in the console (screenshot below)

**Screenshots**
![Screenshot 2019-07-24 16 49 58](https://user-images.githubusercontent.com/5858018/61771551-76ba5980-ae33-11e9-8650-c17102f254e2.png)

**Comment by tilanka** [comment]
Interestingly there is no issue in the complex example sandbox (https://codesandbox.io/s/m5lxzzpz69). I notice that  sandbox still uses an alpha version of react 16.8 though

**Comment by tannerlinsley** [comment]
This is fixed in the latest push to master

**Comment by tannerlinsley** [comment]
Please note, you have to update the sandbox to the latest version if you have forked it.

**Comment by tannerlinsley** [comment]
Also worth noting, the `useColumns` and `useRows` hooks are no longer required. They are assumed with the usage of `useTable`

**Comment by nareshbhatia** [comment]
I am still seeing this problem.
- cloned the latest version of the repo
- ran yarn to install dependencies
- ran both examples locally on master branch - they are both giving this error

![image](https://user-images.githubusercontent.com/1220198/61844914-31b41880-ae6f-11e9-8670-95aa61abbb76.png)

P.S. Is this fix released? Is it in version 6.10.0?
