### ISSUE TITLE
useResizeColumns broken in v7.beta.22 

### ISSUE THREAD

**Issue by ggascoigne** [tannerlinsley/react-table#1681]
The columns still display the resizing styles, but dragging them has no effect.

Easily reproduced in https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/column-resizing

**Comment by tannerlinsley** [comment]
Investigating...

**Comment by ggascoigne** [comment]
FYI I think that:

https://github.com/tannerlinsley/react-table/blob/master/src/plugin-hooks/useResizeColumns.js#L64 should be `...newColumnWidths` and not `...action.columnWidths`, and that https://github.com/tannerlinsley/react-table/blob/master/src/plugin-hooks/useResizeColumns.js#L133 should be `startX: clientX` rather than just `clientX`.

**Comment by tannerlinsley** [comment]
Fixed in beta.23

**Comment by ggascoigne** [comment]
yay though it's a bit weird to see the release before the code is here, and yes, I can see tha tyou release from a private repo.

**Comment by tannerlinsley** [comment]
Yeah, until I can nail down reliable CI release automation, it's manual for now. Usually I'll build/test/release locally, then push the commits (including the auto-incremented package version) to github, eg. The code you're referring to was available just moments after I posted that I fixed it. I also posted that before it was done publishing 😛, so there was even more delay.

**Comment by ggascoigne** [comment]
In case it's not obvious, I really appreciate the amount of time you put into this library, I'm finding the v7 approach really powerful.

**Comment by tannerlinsley** [comment]
Thanks! That’s good to hear. Validating as well.

Tanner Linsley

**Comment by ggascoigne** [comment]
I hate to say this, but as far as I can tell, the column-resizing example is still broken.  I even built it locally in case it was the code sandox not doing the upgrade correctly.

**Comment by eenagy** [comment]
> I hate to say this, but as far as I can tell, the column-resizing example is still broken. I even built it locally in case it was the code sandox not doing the upgrade correctly.

Same for me. This is still definitely broken.

**Comment by tannerlinsley** [comment]
Just tested with versions beta.23 and beta.24 and it's working just fine. Make sure you clear your cache in codesandbox.
